# 日志配置
logging:
    config: classpath:logback-dev.xml
# 邮箱配置
spring:
    mail:
        host: smtp.aliyun.com
        port: 25
        username: ouzezh@aliyun.com
        password:
#        properties:
#            mail.debug: true

# 应用配置文件
ozz:
    myConfig: ENC(XAfcx+f/W0P6a+TILk6641e4mXeuk2NftUBbwIIAbtLPYrdbzWr4kUr3jDZbndY1)
    myMapConfig:
        key1: 1
        key2: 2
    mail:
        mailTo: ouzezh@aliyun.com,ouzezh@aliyun.com
    warn:
        overtimeMillis: 600000

