# 日志配置
logging:
    config: classpath:logback-dev.xml
# 邮箱配置
spring:
    mail:
        host: smtp.yeah.net
        port: 25
        username: noreply_me@yeah.net
        password:
#        properties:
#            mail.debug: true

#    kafka:
#        consumer:
#            auto-offset-reset: earliest
#            enable-auto-commit: true
#            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#            isolation-level: read_committed
#            max-poll-records: 500
#            security.protocol: SASL_PLAINTEXT
#            bootstrap-servers: localhost:9192,localhost:9193
#            properties:
#                sasl.mechanism: PLAIN
#                sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="myUsr" password="myPwd";

# 应用配置文件
ozz:
    myConfig: my config
    myMapConfig:
        key1: 1
        key2: 2
    mail:
        mailTo: noreply_me@yeah.net,noreply_me@yeah.net

