#应用配置文件
ozz:
    myConfig: ENC(XAfcx+f/W0P6a+TILk6641e4mXeuk2NftUBbwIIAbtLPYrdbzWr4kUr3jDZbndY1)

spring:
    mail:
        host: smtp.aliyun.com
        port: 25
        username: ouzezh@aliyun.com
        password:
#        properties:
#            mail:
#                debug: true
