# 日志配置
logging:
    config: classpath:logback-dev.xml
# 邮箱配置
spring:
    mail:
        host: smtp.yeah.net
        port: 25
        username: noreply_me@yeah.net
        password:
#        properties:
#            mail.debug: true

# 应用配置文件
ozz:
    myConfig: ENC(EPJXbH4RkwPSR8EKyUVQjcROyYQgpE3vCJWOFJ587W+A7D0u1FnvLoC0MsoO2iAG)
    myMapConfig:
        key1: 1
        key2: 2
    mail:
        mailTo: noreply_me@yeah.net,noreply_me@yeah.net

